# Generated by Django 4.0.1 on 2022-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messsage',
            field=models.TextField(default='Hi', max_length=120),
        ),
    ]
