# Generated by Django 4.0.1 on 2022-01-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageToSend',
            field=models.TextField(max_length=120),
        ),
    ]
