# Generated by Django 4.0.1 on 2022-02-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_messsage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messsage',
            new_name='message',
        ),
    ]
